name = "MAC"
version = "1.0.0"
license = "GNU General Public License v3.0"
author = "Álvaro R. Puente-Uriona"
maintainer = "alvaro.ruiz@ehu.eus"
copyright = "Copyright 2024, Álvaro R. Puente-Uriona"

[library]
source-dir="src"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
test-drive.tag = "v0.4.0"
